apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: frontend
build:
  artifacts:
    #- image: frontend
    - image: gitlab.lnu.se:5050/2dv013/student/team-2024-14-minccino/frontend
      docker:
        dockerfile: Dockerfile.prod
manifests:
  rawYaml:
    - k8s/ingress.yaml
    - k8s/frontend.yaml
deploy:
  kubectl: {}

# Production profile
# A slightly modyfied ingress configuration needed in production.
profiles:
- name: production
  patches:
  - op: replace 
    path: /manifests/rawYaml/0  # JSON Pointer to ingress.yaml
    value: k8s/ingress.yaml  # The value for the ingressClassName field is added in this one